# Reading & Writing Files in Pandas

## CSV Files

### Read CSV
```python
df = pd.read_csv("data.csv")
```

Options:
```python
pd.read_csv("data.csv", usecols=["Name", "Age"], nrows=10)
```

### Write CSV
```python
df.to_csv("output.csv", index=False)
```

---

## Excel Files

### Read Excel
```python
df = pd.read_excel("data.xlsx")
```

Options:
```python
pd.read_excel("data.xlsx", sheet_name="Sales")
```

### Write Excel
```python
df.to_excel("output.xlsx", index=False)
```

Multiple sheets:
```python
with pd.ExcelWriter("report.xlsx") as writer:
    df1.to_excel(writer, sheet_name="Summary", index=False)
    df2.to_excel(writer, sheet_name="Details", index=False)
```

---

## JSON Files

### Read JSON
```python
df = pd.read_json("data.json")
```


## Summary

- `read_*` and `to_*` methods for CSV, Excel, JSON
- Use `sheet_name` for Excel

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df = df[df['IMDb']>6.0]

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df.to_csv("data_updated.csv", index=False)

In [24]:
data = pd.read_json("data.json")

In [25]:
data

,id,name,age,city,salary,department,experience_years,performance_score,email,active
0,1,User_1,48,Kolkata,61894,HR,9,1.48,user1@example.com,True
1,2,User_2,42,Kolkata,35714,Operations,5,1.23,user2@example.com,True
2,3,User_3,37,Pune,62293,HR,7,3.96,user3@example.com,True
3,4,User_4,45,Mumbai,89321,Operations,8,3.35,user4@example.com,False
4,5,User_5,28,Chennai,107768,HR,2,1.50,user5@example.com,True
...,...,...,...,...,...,...,...,...,...,...
345,346,User_346,37,Delhi,69050,HR,14,1.15,user346@example.com,False
346,347,User_347,50,Bangalore,66928,Operations,7,1.03,user347@example.com,False
347,348,User_348,30,Pune,49925,IT,14,1.95,user348@example.com,True
348,349,User_349,48,Kolkata,114926,Operations,2,4.30,user349@example.com,True
349,350,User_350,21,Bangalore,73501,Operations,8,1.55,user350@example.com,False

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 350 non-null    int64
 1   name               350 non-null    object
 2   age                350 non-null    int64
 3   city               350 non-null    object
 4   salary             350 non-null    int64
 5   department         350 non-null    object
 6   experience_years   350 non-null    int64
 7   performance_score  350 non-null    float64
 8   email              350 non-null    object
 9   active             350 non-null    bool
dtypes: bool(1), float64(1), int64(4), object(4)
memory usage: 25.1+ KB

In [28]:
data = [
    {"id": 1, "name": "Alice", "address": {"city": "Delhi", "zipcode": "110001"}},
    {"id": 2, "name": "Bob", "address": {"city": "Mumbai", "zipcode": "400001"}}
]

In [29]:
df = pd.json_normalize(data)

In [30]:
df

   id   name address.city address.zipcode
0   1  Alice        Delhi          110001
1   2    Bob       Mumbai          400001

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2 non-null      int64
 1   name             2 non-null      object
 2   address.city     2 non-null      object
 3   address.zipcode  2 non-null      object
dtypes: int64(1), object(3)
memory usage: 196.0+ bytes